basePath: /
definitions: {}
info:
    description: 'TypeScript + Express API Server'
    title: 'API - Documentation'
    version: 0.0.0
paths: {}
swagger: '2.0'
securityDefinitions: {}
consumes:
    - application/json
produces:
    - application/json
host: '3000'
